#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
"""Reformat fasta file for ISF.

2013/07/16
Edward Liaw
"""
from __future__ import print_function
from warnings import warn
import argparse
import sys
from fungidb_tools import isf
from Bio import SeqIO


def parse_arguments():
    parser = argparse.ArgumentParser(description=__doc__,
                                     fromfile_prefix_chars='@')
    parser.add_argument('infile',
                        type=argparse.FileType('r'), nargs='?',
                        default=sys.stdin, help='input file')
    parser.add_argument('outfile',
                        type=argparse.FileType('w'), nargs='?',
                        default=sys.stdout, help='output file')
    isf.add_rename_args(parser)
    return parser.parse_args()


def main():
    args = parse_arguments()
    renamer = isf.ContigRenamer.from_args(args)

    with args.infile as infile, args.outfile as outfile:
        for record in SeqIO.parse(infile, 'fasta'):
            record.id = renamer.rename(record.id)
            record.description = ''
            SeqIO.write(record, outfile, 'fasta')


if __name__ == "__main__":
    main()
