#!/usr/bin/env python
"""Generate a chromosome map for a genbank file.

2014/02/07
Edward Liaw
"""
from __future__ import print_function, unicode_literals
from future.builtins import str, int
import sys
import argparse
from Bio import SeqIO


def parse_arguments():
    """Handle command-line arguments.

    Returns:
        args: Arguments passed in from the command-line."""
    parser = argparse.ArgumentParser(description=__doc__,
                                     fromfile_prefix_chars='@')
    parser.add_argument('infile',
                        type=argparse.FileType('r'), nargs='?',
                        default=sys.stdin, help='input file')
    parser.add_argument('outfile',
                        type=argparse.FileType('w'), nargs='?',
                        default=sys.stdout, help='output file')
    return parser.parse_args()


def main():
    args = parse_arguments()

    with args.infile as infile, args.outfile as outfile:
        for i, record in enumerate(SeqIO.parse(infile, 'genbank')):
            print("{0}\t{1}\t{1}".format(record.name, i+1), file=outfile)


if __name__ == "__main__":
    main()
